export const CUSTOMER_LOGIN_STARTED = "CUSTOMER_LOGIN_STARTED";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAILED = "CUSTOMER_LOGIN_FAILED";

export const FETCH_LISTINGS_STARTED = "FETCH_LISTINGS_STARTED";
export const FETCH_LISTINGS_SUCCESS = "FETCH_LISTINGS_SUCCESS";
export const FETCH_LISTINGS_FAILED = "FETCH_LISTINGS_FAILED";

export const CUSTOMER_SIGNUP_STARTED = "CUSTOMER_SIGNUP_STARTED";
export const CUSTOMER_SIGNUP_SUCCESS = "CUSTOMER_SIGNUP_SUCCESS";
export const CUSTOMER_SIGNUP_FAILED = "CUSTOMER_SIGNUP_FAILED";

export const CUSTOMER_ACTIVATION_STARTED = "CUSTOMER_ACTIVATION_STARTED";
export const CUSTOMER_ACTIVATION_SUCCESS = "CUSTOMER_ACTIVATION_SUCCESS";
export const CUSTOMER_ACTIVATION_FAILED = "CUSTOMER_ACTIVATION_FAILED";

export const FETCH_PROPERTY_DETAILS_STARTED = "FETCH_PROPERTY_DETAILS_STARTED";
export const FETCH_PROPERTY_DETAILS_SUCCESS = "FETCH_PROPERTY_DETAILS_SUCCESS";
export const FETCH_PROPERTY_DETAILS_FAILED = "FETCH_PROPERTY_DETAILS_FAILED";

export const SET_BOOKING_PARAM = "SET_BOOKING_PARAM";

export const APARTMENT_BOOKING_STARTED = "APARTMENT_BOOKING_STARTED";
export const APARTMENT_BOOKING_SUCCESS = "APARTMENT_BOOKING_SUCCESS";
export const APARTMENT_BOOKING_FAILED = "APARTMENT_BOOKING_FAILED";