export const CUSTOMER_LOGIN_STARTED = "CUSTOMER_LOGIN_STARTED";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAILED = "CUSTOMER_LOGIN_FAILED";

export const FETCH_LISTINGS_STARTED = "FETCH_LISTINGS_STARTED";
export const FETCH_LISTINGS_SUCCESS = "FETCH_LISTINGS_SUCCESS";
export const FETCH_LISTINGS_FAILED = "FETCH_LISTINGS_FAILED";